from __future__ import annotations

import socket
import ssl
from datetime import UTC, datetime
from time import perf_counter, sleep
from typing import Any
from urllib.parse import urlparse
from uuid import uuid4

import httpx
from pydantic import BaseModel, Field

from kontur_edo.settings import Settings

TEST_DOCUMENT_FILENAME = "test-kedo.pdf"
TEST_DOCUMENT_TEXT = """Test document for Kontur KEDO signing.

This file was generated by the integration gateway.
"""


class KedoAuthError(RuntimeError):
    pass


class KedoApiError(RuntimeError):
    def __init__(self, stage: str, status_code: int, response_text: str) -> None:
        self.stage = stage
        self.status_code = status_code
        self.response_text = response_text[:500]
        super().__init__(f"{stage} failed with HTTP {status_code}: {self.response_text}")


class KedoOrganization(BaseModel):
    id: str
    name: str | None = None
    short_name: str | None = None
    inn: str | None = None
    kpp: str | None = None


class KedoEmployee(BaseModel):
    id: str
    org_id: str | None = None
    user_id: str | None = None
    full_name: str | None = None
    login: str | None = None


class KedoEmployeesResponse(BaseModel):
    org_id: str
    employees: list[KedoEmployee]


class KedoSignatureTypesResponse(BaseModel):
    signature_types: list[str]


class KedoDocumentType(BaseModel):
    id: str
    name: str | None = None
    is_default: bool = False
    is_disabled: bool = False
    is_formalized: bool = False
    metadata: dict[str, Any] = Field(default_factory=dict)


class KedoDocumentTypesResponse(BaseModel):
    org_id: str
    document_types: list[KedoDocumentType]


class KedoTestDocumentResponse(BaseModel):
    org_id: str
    employee_id: str
    document_type_id: str
    file_name: str
    content_location: str | None
    processed_content_location: str | None
    process_ids: list[str]
    raw_response: list[dict[str, Any]]


class KedoConnectivityResponse(BaseModel):
    url: str
    host: str
    port: int
    resolved_addresses: list[str]
    dns_error: str | None = None
    tcp_connected: bool = False
    tcp_error: str | None = None
    tls_connected: bool = False
    tls_version: str | None = None
    tls_error: str | None = None
    elapsed_ms: int


def send_test_document(
    settings: Settings,
    *,
    access_token: str | None = None,
    document_type_id: str | None = None,
    sender_id: str | None = None,
    employee_id: str | None = None,
    signature_type: str | None = None,
    due_days: int | None = None,
    file_name: str | None = None,
    file_bytes: bytes | None = None,
) -> KedoTestDocumentResponse:
    token = access_token or authenticate_with_password(settings)
    api_key = _api_key(settings)

    with httpx.Client(base_url=_base_url(settings), timeout=60.0) as client:
        org_id = settings.kedo_org_id or _get_first_organization(
            client, settings, token, api_key
        ).id
        employee_id = employee_id or settings.kedo_employee_id or _get_current_employee(
            client, settings, token, api_key, org_id
        ).id
        sender_id = sender_id or employee_id
        document_type_id = document_type_id or settings.kedo_document_type_id
        document_type_id = document_type_id or _get_document_type(
            client,
            settings,
            token,
            api_key,
            org_id,
        ).id

        file_name = file_name or settings.kedo_test_filename or TEST_DOCUMENT_FILENAME
        content = _upload_content(
            client,
            settings,
            token,
            api_key,
            org_id,
            file_name,
            file_bytes if file_bytes is not None else _test_document_bytes(settings, file_name),
        )
        content["name"] = file_name

        processed_content = _process_content(
            client,
            settings,
            token,
            api_key,
            org_id,
            document_type_id,
            content,
        )
        processed_content["name"] = processed_content.get("name") or file_name

        process_payload = _build_process_payload(
            settings,
            sender_id=sender_id,
            employee_id=employee_id,
            document_type_id=document_type_id,
            content=processed_content,
            signature_type=signature_type,
            due_days=due_days,
        )
        processes_response = _request(
            client,
            "Create KEDO signing process",
            "POST",
            _api_path(settings, f"/kedo/api/v1/orgs/{org_id}/processes"),
            params={"flat": False},
            headers=_json_headers(token, api_key),
            json=process_payload,
        )

    raw_processes = _as_object_list(processes_response.json())
    return KedoTestDocumentResponse(
        org_id=org_id,
        employee_id=employee_id,
        document_type_id=document_type_id,
        file_name=file_name,
        content_location=_string_value(content, "location"),
        processed_content_location=_string_value(processed_content, "location"),
        process_ids=[
            process_id
            for process in raw_processes
            if (process_id := _string_value(process, "id")) is not None
        ],
        raw_response=raw_processes,
    )


def check_connectivity(settings: Settings, *, timeout: float = 10.0) -> KedoConnectivityResponse:
    started_at = perf_counter()
    parsed_url = urlparse(_base_url(settings))
    host = parsed_url.hostname or ""
    port = parsed_url.port or 443
    resolved_addresses: list[str] = []
    dns_error: str | None = None
    tcp_error: str | None = None
    tls_error: str | None = None
    tcp_connected = False
    tls_connected = False
    tls_version: str | None = None

    try:
        resolved_addresses = sorted(
            {
                address[4][0]
                for address in socket.getaddrinfo(host, port, type=socket.SOCK_STREAM)
                if isinstance(address[4][0], str)
            }
        )
    except OSError as error:
        dns_error = f"{type(error).__name__}: {error}"

    try:
        with socket.create_connection((host, port), timeout=timeout) as raw_socket:
            tcp_connected = True
            context = ssl.create_default_context()
            with context.wrap_socket(raw_socket, server_hostname=host) as tls_socket:
                tls_connected = True
                tls_version = tls_socket.version()
    except (OSError, TimeoutError, ssl.SSLError) as error:
        error_message = f"{type(error).__name__}: {error}"
        if tcp_connected:
            tls_error = error_message
        else:
            tcp_error = error_message

    return KedoConnectivityResponse(
        url=_base_url(settings),
        host=host,
        port=port,
        resolved_addresses=resolved_addresses,
        dns_error=dns_error,
        tcp_connected=tcp_connected,
        tcp_error=tcp_error,
        tls_connected=tls_connected,
        tls_version=tls_version,
        tls_error=tls_error,
        elapsed_ms=round((perf_counter() - started_at) * 1000),
    )


def _test_document_bytes(settings: Settings, file_name: str) -> bytes:
    if settings.kedo_test_text:
        return settings.kedo_test_text.encode("utf-8")
    if file_name.casefold().endswith(".pdf"):
        return _build_pdf_bytes("Test document for Kontur KEDO signing.")
    return TEST_DOCUMENT_TEXT.encode("utf-8")


def _build_pdf_bytes(text: str) -> bytes:
    escaped_text = text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
    escaped_text = escaped_text.encode("ascii", errors="replace").decode("ascii")
    stream = f"BT /F1 18 Tf 72 760 Td ({escaped_text}) Tj ET\n".encode("ascii")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>\n",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>\n",
        (
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
            b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\n"
        ),
        (
            b"<< /Length "
            + str(len(stream)).encode("ascii")
            + b" >>\nstream\n"
            + stream
            + b"endstream\n"
        ),
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\n",
    ]

    chunks = [b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"]
    offsets: list[int] = []
    for index, pdf_object in enumerate(objects, start=1):
        offsets.append(sum(len(chunk) for chunk in chunks))
        chunks.append(f"{index} 0 obj\n".encode("ascii") + pdf_object + b"endobj\n")

    xref_offset = sum(len(chunk) for chunk in chunks)
    xref_rows = [b"0000000000 65535 f \n"]
    xref_rows.extend(f"{offset:010d} 00000 n \n".encode("ascii") for offset in offsets)
    chunks.extend(
        [
            b"xref\n",
            f"0 {len(objects) + 1}\n".encode("ascii"),
            *xref_rows,
            b"trailer\n",
            f"<< /Size {len(objects) + 1} /Root 1 0 R >>\n".encode("ascii"),
            b"startxref\n",
            f"{xref_offset}\n".encode("ascii"),
            b"%%EOF\n",
        ]
    )
    return b"".join(chunks)


def authenticate_with_password(settings: Settings) -> str:
    login = settings.kedo_login or settings.login
    password = settings.kedo_password or settings.password
    if not login or not password:
        raise KedoAuthError(
            "KONTUR_LOGIN and KONTUR_PASSWORD must be configured or user must sign in."
        )

    api_key = _api_key(settings)
    with httpx.Client(base_url=_base_url(settings), timeout=30.0) as client:
        response = _request(
            client,
            "KEDO password authentication",
            "POST",
            _api_path(settings, "/kedo/api/v1/authenticate"),
            headers={
                "Accept": "application/json",
                "Content-Type": "application/json",
                "X-Kontur-ApiKey": api_key,
            },
            json={
                "requestType": "Login",
                "login": login,
                "password": password,
            },
        )

    payload = response.json()
    access_token = payload.get("accessToken") if isinstance(payload, dict) else None
    if not isinstance(access_token, str) or not access_token:
        raise KedoAuthError("KEDO authentication response does not contain accessToken.")

    return access_token


def get_organizations(settings: Settings, access_token: str) -> list[KedoOrganization]:
    api_key = _api_key(settings)
    with httpx.Client(base_url=_base_url(settings), timeout=30.0) as client:
        return _get_organizations(client, settings, access_token, api_key)


def get_document_types(
    settings: Settings,
    *,
    access_token: str | None = None,
) -> KedoDocumentTypesResponse:
    token = access_token or authenticate_with_password(settings)
    api_key = _api_key(settings)

    with httpx.Client(base_url=_base_url(settings), timeout=30.0) as client:
        org_id = settings.kedo_org_id or _get_first_organization(
            client, settings, token, api_key
        ).id
        document_types = _get_document_types(
            client,
            settings,
            token,
            api_key,
            org_id,
            include_disabled=True,
            include_systems=True,
            page_size=100,
        )

    return KedoDocumentTypesResponse(org_id=org_id, document_types=document_types)


def get_employees(
    settings: Settings,
    *,
    access_token: str | None = None,
) -> KedoEmployeesResponse:
    token = access_token or authenticate_with_password(settings)
    api_key = _api_key(settings)

    with httpx.Client(base_url=_base_url(settings), timeout=30.0) as client:
        org_id = settings.kedo_org_id or _get_first_organization(
            client, settings, token, api_key
        ).id
        try:
            employees = _get_organization_employees(client, settings, token, api_key, org_id)
        except KedoApiError as error:
            if error.status_code != 404:
                raise
            employees = _get_current_user_employees(client, settings, token, api_key)
        employees = [
            employee
            for employee in employees
            if employee.org_id is None or employee.org_id == org_id
        ]

    return KedoEmployeesResponse(org_id=org_id, employees=employees)


def get_signature_types(settings: Settings) -> KedoSignatureTypesResponse:
    return KedoSignatureTypesResponse(signature_types=_signature_types(settings))


def _get_first_organization(
    client: httpx.Client,
    settings: Settings,
    access_token: str,
    api_key: str,
) -> KedoOrganization:
    organizations = _get_organizations(client, settings, access_token, api_key)
    if not organizations:
        raise KedoAuthError("KEDO did not return organizations for the current user.")
    return organizations[0]


def _get_organizations(
    client: httpx.Client,
    settings: Settings,
    access_token: str,
    api_key: str,
) -> list[KedoOrganization]:
    response = _request(
        client,
        "Get KEDO organizations",
        "GET",
        _api_path(settings, "/kedo/api/v1/orgs/my"),
        headers=_json_headers(access_token, api_key),
        params={"limit": 100, "offset": 0},
    )

    payload = response.json()
    return [_normalize_organization(item) for item in _paged_result(payload)]


def _get_current_employee(
    client: httpx.Client,
    settings: Settings,
    access_token: str,
    api_key: str,
    org_id: str,
) -> KedoEmployee:
    employees = _get_current_user_employees(client, settings, access_token, api_key)
    for employee in employees:
        if employee.org_id == org_id:
            return employee

    if employees:
        return employees[0]

    raise KedoAuthError("KEDO did not return an employee for the current user.")


def _get_current_user_employees(
    client: httpx.Client,
    settings: Settings,
    access_token: str,
    api_key: str,
) -> list[KedoEmployee]:
    response = _request(
        client,
        "Get KEDO current user employees",
        "GET",
        _api_path(settings, "/kedo/api/v1/users/my/employees"),
        headers=_json_headers(access_token, api_key),
        params={"limit": 100, "offset": 0, "includeDeleted": False, "includeOccupations": True},
    )

    return [_normalize_employee(item) for item in _paged_result(response.json())]


def _get_organization_employees(
    client: httpx.Client,
    settings: Settings,
    access_token: str,
    api_key: str,
    org_id: str,
) -> list[KedoEmployee]:
    response = _request(
        client,
        "Get KEDO organization employees",
        "GET",
        _api_path(settings, f"/kedo/api/v1/orgs/{org_id}/employees"),
        headers=_json_headers(access_token, api_key),
        params={"limit": 100, "offset": 0, "includeDeleted": False, "includeOccupations": True},
    )

    return [_normalize_employee(item) for item in _paged_result(response.json())]


def _get_document_type(
    client: httpx.Client,
    settings: Settings,
    access_token: str,
    api_key: str,
    org_id: str,
) -> KedoDocumentType:
    document_types = _get_document_types(
        client,
        settings,
        access_token,
        api_key,
        org_id,
        include_disabled=False,
        include_systems=False,
        page_size=50,
    )
    preferred_name = settings.kedo_document_type_name
    if preferred_name:
        lowered_name = preferred_name.casefold()
        for document_type in document_types:
            if (document_type.name or "").casefold() == lowered_name:
                return document_type

    enabled = [document_type for document_type in document_types if not document_type.is_disabled]
    non_formalized = [document_type for document_type in enabled if not document_type.is_formalized]
    for document_type in non_formalized:
        if document_type.is_default:
            return document_type

    if non_formalized:
        return non_formalized[0]
    if enabled:
        return enabled[0]

    raise KedoAuthError("KEDO did not return enabled document types.")


def _get_document_types(
    client: httpx.Client,
    settings: Settings,
    access_token: str,
    api_key: str,
    org_id: str,
    *,
    include_disabled: bool,
    include_systems: bool,
    page_size: int,
) -> list[KedoDocumentType]:
    document_types: list[KedoDocumentType] = []
    offset = 0
    while True:
        response = _request(
            client,
            "Get KEDO document types",
            "GET",
            _api_path(settings, f"/kedo/api/v1/orgs/{org_id}/document-types"),
            headers=_json_headers(access_token, api_key),
            params={
                "limit": page_size,
                "offset": offset,
                "includeDeleted": False,
                "includeDisabled": include_disabled,
                "includeSystems": include_systems,
            },
        )

        page = [_normalize_document_type(item) for item in _paged_result(response.json())]
        document_types.extend(page)
        if len(page) < page_size:
            return document_types
        offset += page_size


def _upload_content(
    client: httpx.Client,
    settings: Settings,
    access_token: str,
    api_key: str,
    org_id: str,
    file_name: str,
    file_bytes: bytes,
) -> dict[str, Any]:
    response = _request(
        client,
        "Upload KEDO document content",
        "POST",
        _api_path(settings, f"/kedo/api/v1/orgs/{org_id}/contents"),
        headers={
            **_json_headers(access_token, api_key),
            "Content-Type": "application/octet-stream",
            "Content-Disposition": f'attachment; filename="{file_name}"',
        },
        content=file_bytes,
    )

    payload = response.json()
    if not isinstance(payload, dict):
        raise KedoApiError("Upload KEDO document content", 502, "Unexpected non-object response.")
    if _string_value(payload, "location") is None:
        raise KedoApiError(
            "Upload KEDO document content", 502, "Response does not contain location."
        )
    return dict(payload)


def _process_content(
    client: httpx.Client,
    settings: Settings,
    access_token: str,
    api_key: str,
    org_id: str,
    document_type_id: str,
    content: dict[str, Any],
) -> dict[str, Any]:
    response = _request(
        client,
        "Start KEDO document content processing",
        "POST",
        _api_path(settings, f"/kedo/api/v1/orgs/{org_id}/documents/process/tasks"),
        headers=_json_headers(access_token, api_key),
        json={
            "content": content,
            "documentTypeId": document_type_id,
        },
    )

    payload = _wait_for_content_processing_result(
        client,
        settings,
        access_token,
        api_key,
        org_id,
        response.json(),
    )
    if not isinstance(payload, dict):
        raise KedoApiError("Process KEDO document content", 502, "Unexpected non-object response.")

    error_type = payload.get("errorType")
    if isinstance(error_type, str) and error_type:
        raise KedoApiError("Process KEDO document content", 422, error_type)

    processed_content = payload.get("content")
    if not isinstance(processed_content, dict) and _string_value(payload, "location") is not None:
        processed_content = payload
    processed_content = processed_content or content
    if not isinstance(processed_content, dict):
        raise KedoApiError(
            "Process KEDO document content", 502, "Response content is not an object."
        )
    return dict(processed_content)


def _wait_for_content_processing_result(
    client: httpx.Client,
    settings: Settings,
    access_token: str,
    api_key: str,
    org_id: str,
    task_payload: Any,
    *,
    timeout_seconds: float = 60.0,
    poll_interval_seconds: float = 1.0,
) -> dict[str, Any]:
    if not isinstance(task_payload, dict):
        raise KedoApiError(
            "Process KEDO document content", 502, "Unexpected non-object task response."
        )

    task_id = _string_value(task_payload, "id")
    started_at = perf_counter()
    payload = task_payload
    while True:
        status = _string_value(payload, "status")
        if status == "Complete":
            result = payload.get("result")
            if not isinstance(result, dict):
                raise KedoApiError(
                    "Process KEDO document content", 502, "Task result is not an object."
                )
            return result

        if status in {"Failed", "Unknown"}:
            result = payload.get("result")
            error_type = result.get("errorType") if isinstance(result, dict) else None
            message = error_type if isinstance(error_type, str) and error_type else status
            raise KedoApiError("Process KEDO document content", 422, message)

        if not task_id:
            raise KedoApiError(
                "Process KEDO document content", 502, "Task response does not contain id."
            )
        if perf_counter() - started_at >= timeout_seconds:
            raise KedoApiError(
                "Process KEDO document content", 504, "Content processing task timed out."
            )

        sleep(poll_interval_seconds)
        response = _request(
            client,
            "Get KEDO document content processing result",
            "GET",
            _api_path(settings, f"/kedo/api/v1/orgs/{org_id}/documents/process/tasks/{task_id}"),
            headers=_json_headers(access_token, api_key),
        )
        payload = response.json()
        if not isinstance(payload, dict):
            raise KedoApiError(
                "Process KEDO document content", 502, "Unexpected non-object task response."
            )


def _build_process_payload(
    settings: Settings,
    *,
    sender_id: str,
    employee_id: str,
    document_type_id: str,
    content: dict[str, Any],
    signature_type: str | None,
    due_days: int | None,
) -> dict[str, Any]:
    signature_types = [signature_type] if signature_type else _signature_types(settings)
    safe_due_days = max(due_days or 1, 1)
    sender_target = {"type": "Employee", "id": sender_id}
    signer_target = {"type": "Employee", "id": employee_id}
    signer_route = {
        "type": "Sign",
        "id": str(uuid4()),
        "target": signer_target,
        "documentKeys": [1],
        "allowedTypes": signature_types,
        "allowedActions": ["Admission", "Rejection"],
        "deadline": {
            "relativeDeadlineAt": safe_due_days,
        },
    }
    sender_sign_route = {
        "type": "Sign",
        "id": str(uuid4()),
        "target": sender_target,
        "documentKeys": [1],
        "allowedTypes": signature_types,
        "allowedActions": ["Admission", "Rejection"],
        "next": signer_route,
    }
    sender_route = {
        "type": "NoAction",
        "id": str(uuid4()),
        "target": sender_target,
        "next": sender_sign_route,
    }

    return {
        "processes": [
            {
                "name": f"KEDO test document {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}",
                "documents": {
                    "1": {
                        "typeId": document_type_id,
                        "content": content,
                    },
                },
                "route": sender_route,
            }
        ]
    }


def _signature_types(settings: Settings) -> list[str]:
    return [
        signature_type.strip()
        for signature_type in settings.kedo_signature_types.split(",")
        if signature_type.strip()
    ] or ["Pep"]


def _normalize_organization(item: dict[str, Any]) -> KedoOrganization:
    return KedoOrganization(
        id=_required_string(item, "id"),
        name=_string_value(item, "name"),
        short_name=_string_value(item, "shortName"),
        inn=_string_value(item, "inn"),
        kpp=_string_value(item, "kpp"),
    )


def _normalize_employee(item: dict[str, Any]) -> KedoEmployee:
    user = item.get("user")
    user_payload = user if isinstance(user, dict) else {}
    full_name = " ".join(
        value
        for value in (
            _string_value(user_payload, "lastName"),
            _string_value(user_payload, "firstName"),
            _string_value(user_payload, "middleName"),
        )
        if value
    )

    return KedoEmployee(
        id=_required_string(item, "id"),
        org_id=_string_value(item, "orgId"),
        user_id=_string_value(item, "userId"),
        full_name=full_name or None,
        login=_string_value(user_payload, "login"),
    )


def _normalize_document_type(item: dict[str, Any]) -> KedoDocumentType:
    metadata = item.get("metadata")
    metadata_payload = metadata if isinstance(metadata, dict) else {}

    return KedoDocumentType(
        id=_required_string(item, "id"),
        name=_string_value(item, "name"),
        is_default=bool(item.get("isDefault")),
        is_disabled=bool(item.get("isDisabled")),
        is_formalized=bool(metadata_payload.get("isFormalized")),
        metadata=metadata_payload,
    )


def _paged_result(payload: Any) -> list[dict[str, Any]]:
    if not isinstance(payload, dict):
        return []
    result = payload.get("result")
    if not isinstance(result, list):
        return []
    return [item for item in result if isinstance(item, dict)]


def _as_object_list(payload: Any) -> list[dict[str, Any]]:
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if isinstance(payload, dict):
        return [payload]
    return []


def _required_string(payload: dict[str, Any], key: str) -> str:
    value = _string_value(payload, key)
    if value is None:
        raise KedoAuthError(f"KEDO response does not contain required field {key}.")
    return value


def _string_value(payload: dict[str, Any], key: str) -> str | None:
    value = payload.get(key)
    return value if isinstance(value, str) and value else None


def _raise_for_status(response: httpx.Response, stage: str) -> None:
    if response.is_success:
        return
    raise KedoApiError(stage, response.status_code, response.text.strip())


def _request(
    client: httpx.Client,
    stage: str,
    method: str,
    url: str,
    **kwargs: Any,
) -> httpx.Response:
    try:
        response = client.request(method, url, **kwargs)
    except httpx.HTTPError as error:
        raise KedoApiError(stage, 0, f"{type(error).__name__}: {error}") from error

    _raise_for_status(response, stage)
    return response


def _json_headers(access_token: str, api_key: str) -> dict[str, str]:
    return {
        "Accept": "application/json",
        "Authorization": f"Bearer {access_token}",
        "X-Kontur-ApiKey": api_key,
    }


def _api_key(settings: Settings) -> str:
    api_key = settings.kedo_api_key or settings.client_secret or settings.api_key
    if not api_key:
        raise KedoAuthError(
            "KONTUR_KEDO_API_KEY, KONTUR_CLIENT_SECRET or KONTUR_API_KEY must be configured."
        )
    return api_key


def _base_url(settings: Settings) -> str:
    return str(settings.kedo_base_url).rstrip("/")


def _api_path(settings: Settings, path: str) -> str:
    base_path = urlparse(_base_url(settings)).path.rstrip("/").casefold()
    if base_path.endswith("/kedo") and path.startswith("/kedo/"):
        return path.removeprefix("/kedo")
    return path
